# Generated by Django 4.1.5 on 2023-02-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_before',
        ),
    ]
