# Generated by Django 4.1.5 on 2023-02-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shop', '0003_rename_price_product_price_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_before',
            new_name='price',
        ),
    ]
