# Generated by Django 4.1.5 on 2023-02-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('cart_shop', '0004_rename_price_before_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemshop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitemshop',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_shop.product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
